name: Teste com Mocha

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.Js
      uses: actions/setup-mode@v3
      with:
        node-version: '16'
    
    - name: Instalar dependências
      run: npm install

    - name: Garantir pemrissões de execução para Mocha
      run: chmod +x ./node_modules/.bin/mocha

    - name: Verificar o caminho do Mocha
      run: Is -I ./node_modules/.bin/mocha

    - name: Rodar os testes com Mocha
      run: npx mocha
